title: Animation with GNUPLOT
description: An Introduction to visulaization of Physical system
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight

author: Arabindo
author_url: #
email: 'mailto:arabindo@pm.me'
